### PR TITLE
changes title, adds description field.

### PR DESCRIPTION
**Pull request by henryk69**
# Updates

title and description text

### CODE REVIEW

**Review by dizak — DISMISSED** [review]
These lines are too long, the menu container takes up to 3/4 of the site's width.

**Comment by dizak** [comment]
With the scss of the sidebar changed, it should display properly. The sidebar width should be no less than the longest single word, that's all. That's why I am dismissing my own review as irrelevant.

**Comment by dizak** [comment]
@henryk69 @Setnea please update the branch and test it.

**Review by dizak — COMMENTED** [review]
I believe there is a typo in the description - there is the ```@``` sign.

**Comment by henryk69** [comment]
@dizak 
thats no typo!

bio and cheminformatics at work -

meaning we can see it working, and we use it in our work (production environment) 

got it?

**Review by dizak — APPROVED** [review]
Seems OK for me

**Pull request merged**
